### ISSUE TITLE
How to do within cluster differential analysis

### ISSUE THREAD

**Issue by jianxinwang** [const-ae/glmGamPoi#38]
Hi, I have a single cell project.  basically, we have two treatment conditions and the two seurat objects are merged. I would like to identify differentially expressed genes within (as opposed to between) a cluster between treatment and control samples. Since there is no replicates per treatment, there is no way to specify the pseudobulk_by parameter. I can not find an example code in your documentation. Can you tell me how to do this type of analysis? Thanks!

**Comment by const-ae** [comment]
Hi jianxinwang,

the problem is that without replicates, it's impossible to find out how much the expression of each individual gene varies. Accordingly, there is also no way to tell if the difference between treated and control condition is significant.

Sorry that I could not be more helpful.

Best Regards,
Constantin
