### ISSUE TITLE
Score and Hessian (of the likelihood function)

### ISSUE THREAD

**Issue by hanbin973** [const-ae/glmGamPoi#43]
Hi,

Let X (nxp matrix) be the design matrix
I'm wondering if the sum of scores (sum over n, pxp matrix) and sum of hessians (sum over n, pxp matrix) are directly available.
These values seem to be computed internally while fitting the model but does not seem to be present in the glm_gp object. 
I know it can be computed using the predict and additional matrix operations but thought the process was redundant since it's already computed while fitting.

Thanks.

**Comment by const-ae** [comment]
Hi Hanbin,

thank you for your interest. I chose the return values based on what is useful for the "average" user. Returning more internal values (e.g. the Hessian for each gene) would lead to large output objects with little benefit to the normal user.

Depending on your use-case, you could consider forking the package and modifying it, so that it returns the values that you need. I would recommend to take a look at the `fisher_scoring_qr_step()` function to extract for example the score vector.

Best,
Constantin
