### ISSUE TITLE
update tag on blog

### ISSUE THREAD

**Issue by jan-glx** [const-ae/glmGamPoi#8]
On (https://const-ae.name/post/need_for_speed-deseq2/) you recommend installing 
 `devtools::install_github("mikelove/DESeq2@ae7c6bd")` to try the speedups, since your changes have been merged & there have been some bugs in that version you might want to change that to  `remotes::install_github("mikelove/DESeq2")`.

**Comment by const-ae** [comment]
Hey Jan,

thank you for the notification. I updated the the blog-post https://const-ae.name/post/need_for_speed-deseq2/.

Just so that there is no confusion, that blog post had nothing to do yet with `glmGamPoi`. The changes that allow you to call `glmGamPoi` from `DESeq2` were introduced later :)

Best, Constantin

**Comment by jan-glx** [comment]
Thanks & thanks for the clarification, I indeed thought they were related & couldn't find a more appropriate place to give feedback on the blog.
